<a href="https://colab.research.google.com/github/vrajsavliya/ml_learning/blob/main/numpy_tricks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

np.sort


In [2]:
import numpy as np
a = np.random.randint(1,100,15)
a

array([10, 49, 80, 84, 91, 18,  9, 17, 51, 35, 62, 70, 95, 54,  6])

In [3]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[46, 22, 66, 68],
       [56, 44, 67, 47],
       [28, 71, 38, 18],
       [59, 78, 37, 40],
       [35, 61, 92, 99],
       [ 2, 85, 39, 39]])

In [8]:
np.sort(b,axis=1)[::-1]

array([[ 2, 39, 39, 85],
       [35, 61, 92, 99],
       [37, 40, 59, 78],
       [18, 28, 38, 71],
       [44, 47, 56, 67],
       [22, 46, 66, 68]])

In [9]:
# np.append

np.append(a,100)

array([ 10,  49,  80,  84,  91,  18,   9,  17,  51,  35,  62,  70,  95,
        54,   6, 100])

In [12]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[46., 22., 66., 68.,  1.],
       [56., 44., 67., 47.,  1.],
       [28., 71., 38., 18.,  1.],
       [59., 78., 37., 40.,  1.],
       [35., 61., 92., 99.,  1.],
       [ 2., 85., 39., 39.,  1.]])

In [13]:
np.unique(a)

array([ 6,  9, 10, 17, 18, 35, 49, 51, 54, 62, 70, 80, 84, 91, 95])

In [14]:
# np.where  here we get the index
np.where(a > 50)

(array([ 2,  3,  4,  8, 10, 11, 12, 13]),)