<a href="https://colab.research.google.com/github/vrajsavliya/ml_learning/blob/main/numpy_basic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ways to create different types of arrays

In [ ]:
#np.array ---> use to create a array
import numpy as np

a = np.array([1,2,3]) # This is a 1D array
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [ ]:
# 2D and 3D array can also be made using the nparray

b = np.array([[1,2,3],[4,5,6]])
print(b)

# tensor is a 3D numpy array

c = np.array([[[1,2],[3,4]],[[2,3],[5,6]]])
print("this is a tensor \n",c)

[[1 2 3]
 [4 5 6]]
this is a tensor 
 [[[1 2]
  [3 4]]

 [[2 3]
  [5 6]]]


In [ ]:
# Lets make a float data type array using np using dtype=float
# can be made the bool and in python all the values are consider true in all the positive numbers
# and complex is the (num + i) yee vala format dekh loo change krr ke dtype me

d = np.array([1,2,3],dtype=bool)
print("float Array",d)

float Array [ True  True  True]


In [ ]:
# np.arange to use in the loops

np.arange(1,11) # ye deta hai (start, end - 1);
np.arange(1,11,2) # ye 2 hai voo i++ jo haii bus aus ki badle i + 2 karega


array([1, 3, 5, 7, 9])

In [ ]:
# with reshape
np.arange(1,11).reshape(5,2)
# here the imp condition for reshape the product sould be equal to the number count then its possible
# ye reshape mujzee 2D me convert krr ke deta hai ye brackets hai(row,colum)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [ ]:
# np.ones and np.zeros

# np.ones ko use krr ke hum eek go me sare items array me 1 bana sakte hai
np.ones((3,4))
# same for 0 one use the np.zeros
np.zeros((3,4))

#it will be used in the neurals network to initially give all the values

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random

np.random.random((3,4))

array([[0.49703678, 0.47941269, 0.05416963, 0.35520935],
       [0.16840725, 0.70253941, 0.54726137, 0.80034937],
       [0.32452253, 0.79580025, 0.60162697, 0.21708832]])

In [ ]:
# np.linespace(Start_range,End_range,numbers to generate between this range)
# it generate the points in the equal distance
# this is call linearly seperable
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [ ]:
# np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Array Attributes

In [ ]:
a1 = np.arange(10,dtype=np.int32)
print(a1)
a2 = np.arange(12, dtype=float).reshape(3, 4)
print(a2)
a3 = np.arange(8).reshape(2, 2, 2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [ ]:
# ndim --> tells about the dimensions of the array what it has 1,2,3D etc
a1.ndim
a2.ndim
a3.ndim

3

In [ ]:
# shape
# it tell about the numbers of rows col etc the shape of the array

print(a3.shape)

(2, 2, 2)


In [ ]:
# size
# tells about the numbers of items in the array

a1.size

10

In [ ]:
# itemsize

a1.itemsize

4

In [ ]:
# dtype

a1.dtype

dtype('int32')

Changing Datatype

In [ ]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

Array Operations

In [ ]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [ ]:
#scalar operations
# arithmetic operations
a1 + 2 # all will work

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [ ]:
# relations
a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [ ]:
# Vector operations
# arithmetic
a1 *a2

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

Array Functions